Ext.define('MyApp.model.Student', {
        extend: 'Ext.data.Model',
        fields: [
            'studentid',
            'admissionno',
            'admissiontype',
            'admissiondate1',
            'name',
            'fname',
            'mname',
            'lname',
            'dob',
            'address',
            'fathername',
            'mothername',
            'caretakername',
            'parentemailid',
            'parentmobile',
            'alternateemailid',
            'alternatemobile',
            'classid',
            'schoolid',
            'createdby',
            'createdon',
            'modifiedby',
            'modifiedon',
            'religion',
            'cityid',
            'stateid',
            'countryid',
            'userid',
            'gender',
            'nationality',
            'mother_tounge',
            'passport_no',
            'ssn',
            'visadetail',
            'uid',
            'aadhar_id',
            'blood_group','image_path',
            'category','previledged_student','occupation', 'fatherhighestedu', 'motherhishedu', 'annualincome',
            {name:'rollno', type:'int'}
        ]
    });
